### PR TITLE
Add a `done` for the it functions when users want async behaviour

### PR DESCRIPTION
**Pull request by CestDiego**
like this case:

```js
var request = require('supertest');
var expect = require('chai').expect;
var app = require('../server.js').app;


describe("Server", function() {
  it('should respond with 200 for home', function(done){
    request(app)
      .get('/')
      .expect(200, done);
  })
})
```

### CODE REVIEW

**Comment by cowboyd** [comment]
It would definitely be a welcome addittion. Have you considered having a separate snippet like `itdone` that does it in a single go? I'm a bit hesitant to add an extra keystroke to every expansion.

Also, most of the time I use `done` in a `beforeEach` block. We should have a similar expansion for beforeEach

**Comment by CestDiego** [comment]
what about `it.` to the done part and `it` to the one without it? ^ it's pushed already

**Comment by cowboyd** [comment]
Looks good! Also, since we're at it, do the suite-level `before` and `after` hooks also accept the `done` parameter?

**Comment by CestDiego** [comment]
implemented the before and after

**Comment by cowboyd** [comment]
Looks like this broke the expectation. Since it is better practice and more common to use `beforeEach` than `before` I think it deserves the shorter key `bef`:

`bef -> beforeEach(function() {`
`bef. -> beforeEach(function(done) {`
`before -> before(function() {`
`before. -> before(function(done) {`

etc...

**Comment by CestDiego** [comment]
Modified it.

**Pull request merged**
